### ISSUE TITLE
System should be hooked instead of APP

### ISSUE THREAD

**Issue by 006hjy** [Xposed-Modules-Repo/xda.swer45.teehide#1]
hook APP，Xposed will be discovered by APP.You should hook System Framework.

**Comment by swer45** [comment]
If you hook system framework, you will change KeyStore of the system but it will not be affected by apps. I tried it and Key Attestation Demo detect an unlocked bootloader.

**Comment by swer45** [comment]
> hook APP，Xposed will be discovered by APP.You should hook System Framework.

But if you find a way to do this you can share here 😁👍
